#! /usr/bin/bash

# Note: this fails to build the executables, but we only need the
# libraries, which get built before the executables

set -euo pipefail

PHP_WASIX_DEPS="$(pwd)/../php-wasix-deps"
WASIX_SYSROOT=/home/arshia/repos/wasmer/wasix-libc/sysroot32

export \
  CC="clang-15 --target=wasm32-wasi --sysroot=$WASIX_SYSROOT" \
  AR="llvm-ar-15" \
  NM="llvm-nm-15" \
  RANLIB="llvm-ranlib-15" \
  CFLAGS="-matomics -mbulk-memory -mmutable-globals -pthread -mthread-model posix -ftls-model=local-exec \
    -fno-trapping-math -D_WASI_EMULATED_MMAN -D_WASI_EMULATED_SIGNAL -D_WASI_EMULATED_PROCESS_CLOCKS \
    -g -flto -O2" \
  LDFLAGS="-Wl,--shared-memory -Wl,--max-memory=4294967296 -Wl,--import-memory -Wl,--export-dynamic \
    -Wl,--export=__heap_base -Wl,--export=__stack_pointer -Wl,--export=__data_end -Wl,--export=__wasm_init_tls \
    -Wl,--export=__wasm_signal -Wl,--export=__tls_size -Wl,--export=__tls_align -Wl,--export=__tls_base \
    -lwasi-emulated-mman -flto -lz"

./configure \
  --host=x86_64-pc-linux-gnu \
  --enable-png --with-pngincludedir=$PHP_WASIX_DEPS/include/png --with-pnglibdir=$PHP_WASIX_DEPS/lib \
  --enable-jpeg --with-jpegincludedir=$PHP_WASIX_DEPS/include/jpeg --with-jpeglibdir=$PHP_WASIX_DEPS/lib \
  --enable-static --disable-shared
